# Generated by Django 2.1.14 on 2020-02-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_last_name',
        ),
    ]
