# Generated by Django 2.1.14 on 2020-03-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='order_total',
        ),
    ]
