# Generated by Django 2.1.14 on 2020-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200410_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_postcode',
            field=models.CharField(max_length=10),
        ),
    ]
