# Generated by Django 2.1.14 on 2020-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200126_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_serves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
