# Generated by Django 2.1.14 on 2020-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_serves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_serves',
            field=models.IntegerField(),
        ),
    ]
