# Generated by Django 2.1.14 on 2020-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200224_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category_name',
            field=models.TextField(max_length=30),
        ),
    ]
