# Generated by Django 2.1.14 on 2020-02-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('products', '0005_auto_20200224_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
