# Generated by Django 2.1.14 on 2020-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200306_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
